### ISSUE TITLE
Edge artifacts

### ISSUE THREAD

**Issue by rezaparaanczi** [SBC-Utrecht/pytom-match-pick#105]
Hello,

My CC map has peaks only on the edges both when I crop the tomograms manually and also when I use the pytom search-xyz options. Do you have a diagnosis for this? thanks. I have attached the template, the mask, and the score map.
![Screenshot 2024-02-13 at 9 48 30 AM](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/140761740/651a7a60-78e2-454a-88da-f37b32d3dffd)
![Screenshot 2024-02-13 at 9 48 04 AM](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/140761740/ba8fa193-307d-4fbd-9332-59cf834b5d8e)
![Screenshot 2024-02-13 at 9 46 46 AM](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/140761740/daeeeded-162b-43b4-900b-e0eac80f5b00)

**Comment by McHaillet** [comment]
Thanks for attaching the images, that is very helpful! In case you are viewing the score map with IMOD (which looks like it), you need to set the contrast sliders to include the full range of values (see below). IMOD always clips to 3 standard deviation, which is good for viewing tomograms but not the score maps. The score maps have a lot of background compared to hits and with the default contrast they get fully clipped. 

![image](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/58044494/cf8ff109-e926-4582-859a-084b4a0e10c6)

That is my first intuition in this case. Please let me know if it helps.

**Comment by rezaparaanczi** [comment]
Thanks for getting back to me. It's definitely not a brightness/contrast adjustment issue. My understanding is that the real peaks should pop out when those two are adjusted, correct? I also got the same artifact when using --s 2 1 1.
![Screenshot 2024-02-14 at 8 31 08 AM](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/140761740/43cf502e-f723-47d8-9fb5-5dff66d27a3c)

**Comment by rezaparaanczi** [comment]
This is the same area without adjusting brightness contrast.
<img width="563" alt="Screenshot 2024-02-14 at 9 23 01 AM" src="https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/140761740/e58f81c1-902b-4142-b874-3f174843a5c2">

**Comment by McHaillet** [comment]
What version are you running? There was a bug with this in the subvolume splitting, essentially score maps were not correctly merged together in combination with search region cropping. With version 0.3.4 this should be fixed (see also what I mentioned in #101 as reinstalling could also improve your speed). 

> My understanding is that the real peaks should pop out when those two are adjusted, correct?

Exactly, if the localization works well, they should pop out!

You could also compare with a score map from ribosome template matching. But take into account that correlations will likely be significantly less strong with decreasing size. Also its critical that your tomograms are aligned well and CTF corrected (for example with imod ctfphaseflip).

**Comment by rezaparaanczi** [comment]
Thank you so much. How I do get my version information?

Here is how the events unfolded regarding the edge artifact: I was template matching on Bin 8 tomograms. I was getting peaks, similar to how I was getting peaks for ribosomes, but I think they weren't great based on RUC. I did get 230 particles from 10 tomograms and the reconstruction resembled the structure, but I was doubtful that it might be template bias. That's when I switched to Bin 4 tomograms, and started having memory and speed issues. That's when I tried cropping manually, also search-xyz, and also -s 2 1 1, separately. They all had similar edge artifacts and it didn't look anything like the bin 8 CC peaks.

**Comment by McHaillet** [comment]
For the version, run this in a terminal where the conda environment is active: `python -c "import pytom_tm; print(pytom_tm.__version__)"`

**Comment by rezaparaanczi** [comment]
Cool, my version is 0.3.3.

**Comment by McHaillet** [comment]
@rezaparaanczi, did you manage to update the version?

**Comment by rezaparaanczi** [comment]
Sorry not yet. Is there a simple command for that?

**Comment by McHaillet** [comment]
If you installed the software yourself, I advise to do a fresh install with the instructions in the readme (follow option 1 when choosing conda environment setup) and run all the commands. You can remove your previous conda environment with:
```conda env remove -n pytom_tm```
And delete the github download.
If you need more help with, you can also send me a mail m.l.chaillet@uu.nl and we can schedule a call.

Otherwise ask your administrator If they could reinstall with the new installation instructions.

**Comment by McHaillet** [comment]
Will close this issue as the edge artifacts should be solved in the latest versions.
