### ISSUE TITLE
question for angular search

### ISSUE THREAD

**Issue by jinxsfe** [SBC-Utrecht/pytom-match-pick#144]
![image](https://github.com/SBC-Utrecht/pytom-match-pick/assets/121477741/6e2ea88c-7715-465d-97bc-f8b817350dc0)
I dont know how to get 20A when calculate the rmax in tomogram, when I check the online data, the
![image](https://github.com/SBC-Utrecht/pytom-match-pick/assets/121477741/039806e8-5d0a-41fb-a7c0-d60b0c5268f9) voxel size for 
![image](https://github.com/SBC-Utrecht/pytom-match-pick/assets/121477741/f6b5e09b-5995-4600-8d46-cb7c8793f226) these data is 1.0 um in icy and 1 Anstrom for imod, how we get 20A

**Comment by McHaillet** [comment]
First, you are right about the voxel size annotation for the tutorial files, it should totally be: 13.79 Angstrom! Sorry for the mistake there, I though I annotated them properly.

In the tutorial we apply a low pass filter at 40A resolution, which in fourier space is 1/40 $A^{-1}$. Hence the 7.00 degrees sampling. If we would have not applied a low pass filter, the nyquist resolution of the tomogram would be 1/ (2 * 13.79) $A^{-1}$, and the angular sampling would change!

**Comment by McHaillet** [comment]
I added a fix for the voxel size annotation in the tutorial.
