### ISSUE TITLE
make online/public space for questions about how to use

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#152]
Perhaps a google group? User questions and answers can then be found back, as GitHub is an ideal place to retain such discussions.

What do you think, @sroet?

**Comment by sroet** [comment]
We could enable discussions? (https://github.com/SBC-Utrecht/pytom-match-pick/discussions)

**Comment by McHaillet** [comment]
https://github.com/SBC-Utrecht/pytom-match-pick/discussions

**Comment by McHaillet** [comment]
Agreed!
