### ISSUE TITLE
Numpy 2.0 fft updates might be relevant

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#171]
Just a reminder to check if it's relevant:
https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-fft-deprecations-for-n-d-transforms-with-none-values-in-arguments

**Comment by McHaillet** [comment]
This should be updated. Essentially all the irfftn's I used only have the `s` argument and not the `axes` argument. Can I guess be fixed like so:

```
ft = np.fft.rfftn(image)
new_image = np.fft.irfftn(ft, s=image.shape, axes=list(range(image.shape)))
```

**Comment by sroet** [comment]
So from a glance none of our files are affected (so far), I `grep`ed all python files containing :
```
matching.py #only cupy based
weights.py #only np.fft.fftshift and np.fft.ifftshift, not deprecated
template.py # only scipy based
tmjob.py # only scipy based
```

So I think this issue can be closed?

**Comment by McHaillet** [comment]
you're right! Is there a chance that scipy will follow numpy2 convention?

**Comment by sroet** [comment]
Maybe at some point, but I kinda expect them to just implement the `list(range(image.shape))` themselves :crossed_fingers:

**Comment by McHaillet** [comment]
Okay, let's close it!
