### ISSUE TITLE
center of mass not working as expected

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#173]
Maybe this centering option should be reevaluated. I had some small issues with it before. This is the scipy docs for center of mass (https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.center_of_mass.html) the bottom lines say it can return a RuntimeWarning and return inf or nan values, which might be why your template ends up empty.

_Originally posted by @McHaillet in https://github.com/SBC-Utrecht/pytom-match-pick/discussions/172#discussioncomment-9647246_

**Comment by sroet** [comment]
From an offline discussion: Looking at a center of mass code, it looks like it is not behaving as we expect when both positive and and negative voxels are present. We decided to use array**2 to compute the center of mass instead (hopefully also focusing more on the strong data vs noise)
