### ISSUE TITLE
z-axis rotational symmetry

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#180]
Wouter mentioned the rotational symmetry might be incorrect. Currently it is applied along the Z1-axis, but his point was it should be applied along the Z2-axis as the ZXZ angles specify the rotation of the reference onto the particle in the tomogram. Thinking about it he is probably right.

Perhaps fix or remove argument, depending on time?

@sroet maybe you could look at it? Should I assign it?

**Comment by sroet** [comment]
I can look into it, feel free to assign it. 

The symmetry axis of the template is normally the z-axis, right?

**Comment by McHaillet** [comment]
Yes, I assumed the template is oriented with its symmetry axis along the z-axis!

**Comment by sroet** [comment]
Yeah, looking into it we should only reduce the search space of Z2
reference: [slide 14 here (PDF)](https://www.researchgate.net/profile/Gert-Nolze/publication/261217017_Euler_angles_and_symmetry/links/00b7d535365d0590c6000000/Euler-angles-and-symmetry.pdf)

Will implement it!
