### ISSUE TITLE
delete wiki and change links once site is up

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#200]
Once PR #199 is merged and the site is automatically deployed, the wiki can be deleted and some links on https://pytom.sites.uu.nl/ should be updated!

**Comment by McHaillet** [comment]
Perfect! Than we can remove the old wiki!

I noticed the news on that website (https://pytom.sites.uu.nl/news/) is outdated. Maybe we could remove that page?

**Comment by sroet** [comment]
> I noticed the news on that website (https://pytom.sites.uu.nl/news/) is outdated. Maybe we could remove that page?

We should probably discuss offline (or at least off github ) with @FridoF what to do with the website in general

> Than we can remove the old wiki!

I will disable the wiki

**Comment by sroet** [comment]
> I will disable the wiki

This is done
