### ISSUE TITLE
add a citation file to the repository

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#213]
We should probably add a [citation file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) as well

_Originally posted by @sroet in https://github.com/SBC-Utrecht/pytom-match-pick/pull/212#discussion_r1707844983_

**Comment by sroet** [comment]
For my reference, we should use https://citation-file-format.github.io/cff-initializer-javascript/#/
