### ISSUE TITLE
phase shift in CTF to model vpp phase plate 

### ISSUE THREAD

**Issue by PeterVanF** [SBC-Utrecht/pytom-match-pick#76]
Hi, 
I collected some vpp phase plate tomography datasets and would like to try pytom-template matching. I was wondering how to set parameters when using pytom_create_template.py. Is it different from conventional defocus tomography dataset? Do I need to consider the phase shift?  
Best,
Peter

**Comment by McHaillet** [comment]
Hi Peter,
Indeed you would need to consider the phase shift, but currently that option is not implemented. It will definitely be good to add in and should not be hard, as adding the phase shift is a simple modification of the CTF calculation. I have no idea when I have time to add that, so I will leave the issue open for now. 

For now, with the phase plate you do have a lot more low frequency signal, so you could try to leave out the CTF multiplication when preparing the template. Subsequenctly, you can the set a low pass filter in pytom_match_template to remove some high frequencies where the CTF is not modelled.
Best,
Marten

**Comment by PeterVanF** [comment]
I got it. Thank you very much!
