### ISSUE TITLE
question about CUDA version

### ISSUE THREAD

**Issue by jinxsfe** [SBC-Utrecht/pytom-match-pick#80]
For the installation procedure, does cuda version for the environment be done for 11.8?

**Comment by sroet** [comment]
All of the CUDA code is done by `cupy`, so if you have a working installation of a (somewhat recent) `cupy` then this software should work as well. You can test this by running
`python -c "import cupy as cp; a = cp.zeros((100,100))"` 
which should not raise any errors

The installation instructions are specific, because our test systems are build against `11.8`, so you might run into issues we haven't seen if you run newer or older cuda versions.

However, if you run into any issues with newer cuda version please let us know as we should solve those for future use!

**Comment by jinxsfe** [comment]
Hi, thanks , I am run the command for 
![image](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/121477741/dd1e1d2a-e1ab-4b86-88cd-47a7c098c7ba)
, but there is error 
![image](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/121477741/d07f076a-66e3-40aa-9b4c-f520f5f2138d)

**Comment by jinxsfe** [comment]
seems there is code error? instead of package error?raceback (most recent call last):
  File "C:\Windows\system32\pytom-template-matching-gpu\tests\test_tmjob.py", line 232, in test_tm_job_split_volume
    self.assertAlmostEqual(angle_diff, 0, places=1, msg='angle diff should not change')
AssertionError: 8.0 != 0 within 1 places (8.0 difference) : angle diff should not change

**Comment by jinxsfe** [comment]
@sroet

**Comment by jinxsfe** [comment]
ERROR: test_parallel_manager (test00_parallel.TestTMJob.test_parallel_manager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Windows\system32\pytom-template-matching-gpu\tests\test00_parallel.py", line 84, in test_parallel_manager
    score, angle = run_job_parallel(self.job, volume_splits=(1, 3, 1), gpu_ids=[0])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sjc\miniconda3\envs\pytom_tm\Lib\site-packages\pytom_tm\parallel.py", line 107, in run_job_parallel
    raise RuntimeError('One or more of the processes stopped unexpectedly.')
RuntimeError: One or more of the processes stopped unexpectedly.

======================================================================
ERROR: test_search (test_template_matching.TestTM.test_search)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Windows\system32\pytom-template-matching-gpu\tests\test_template_matching.py", line 36, in test_search
    score_volume, angle_volume, stats = tm.run()
                                        ^^^^^^^^
  File "C:\Users\sjc\miniconda3\envs\pytom_tm\Lib\site-packages\pytom_tm\matching.py", line 176, in run
    self.stats['variance'] += (square_sum_kernel(self.plan.ccc_map) / self.plan.volume.size)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\_reduction.pyx", line 828, in cupy._core._reduction.ReductionKernel.__call__
  File "cupy\_core\_reduction.pyx", line 370, in cupy._core._reduction._AbstractReductionKernel._call
  File "cupy\_core\_cub_reduction.pyx", line 689, in cupy._core._cub_reduction._try_to_call_cub_reduction
  File "cupy\_core\_cub_reduction.pyx", line 526, in cupy._core._cub_reduction._launch_cub
  File "cupy\_core\_cub_reduction.pyx", line 461, in cupy._core._cub_reduction._cub_two_pass_launch
  File "cupy\_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy\_core\_cub_reduction.pyx", line 240, in cupy._core._cub_reduction._SimpleCubReductionKernel_get_cached_function
  File "cupy\_core\_cub_reduction.pyx", line 223, in cupy._core._cub_reduction._create_cub_reduction_function
  File "cupy\_core\core.pyx", line 2254, in cupy._core.core.compile_with_cache
  File "C:\Users\sjc\miniconda3\envs\pytom_tm\Lib\site-packages\cupy\cuda\compiler.py", line 484, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sjc\miniconda3\envs\pytom_tm\Lib\site-packages\cupy\cuda\compiler.py", line 562, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sjc\miniconda3\envs\pytom_tm\Lib\site-packages\cupy\cuda\compiler.py", line 319, in compile_using_nvrtc
    return _compile(source, options, cu_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sjc\miniconda3\envs\pytom_tm\Lib\site-packages\cupy\cuda\compiler.py", line 284, in _compile
    options, headers, include_names = _jitify_prep(
                                      ^^^^^^^^^^^^^
  File "C:\Users\sjc\miniconda3\envs\pytom_tm\Lib\site-packages\cupy\cuda\compiler.py", line 233, in _jitify_prep
    jitify._init_module()
  File "cupy\cuda\jitify.pyx", line 212, in cupy.cuda.jitify._init_module
  File "cupy\cuda\jitify.pyx", line 233, in cupy.cuda.jitify._init_module
  File "cupy\cuda\jitify.pyx", line 209, in cupy.cuda.jitify._init_cupy_headers
  File "cupy\cuda\jitify.pyx", line 198, in cupy.cuda.jitify._init_cupy_headers_from_scratch
  File "cupy\cuda\jitify.pyx", line 128, in cupy.cuda.jitify.dump_cache
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\sjc\\.cupy\\jitify_cache\\tmpy1nl4ulx' -> 'C:\\Users\\sjc/.cupy/jitify_cache/jitify_<unknown>_200200_12030_2_708aba36cc76a759012d525e384bad640b360647.json'

======================================================================
FAIL: test_tm_job_split_volume (test_tmjob.TestTMJob.test_tm_job_split_volume)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Windows\system32\pytom-template-matching-gpu\tests\test_tmjob.py", line 232, in test_tm_job_split_volume
    self.assertAlmostEqual(angle_diff, 0, places=1, msg='angle diff should not change')
AssertionError: 8.0 != 0 within 1 places (8.0 difference) : angle diff should not change

----------------------------------------------------------------------
Ran 20 tests in 123.594s

FAILED (failures=1, errors=2)

**Comment by sroet** [comment]
First you should deal with your `cupy` errors, it seems like your install does not work with custom `cupy` kernels.
Running 
```
python -c "import cupy as cp; import numpy as np; sd = cp.ElementwiseKernel('float32 x, float32 y','float32 z', 'z=(x-y)*(x-y)', 'sd'); x=cp.arange(10, dtype=np.float32).reshape(2,5); y=cp.arange(5, dtype=np.float32); print(sd(x,y)); print(sd(x,5))"
```
should print
```
[[ 0.  0.  0.  0.  0.]
 [25. 25. 25. 25. 25.]]
[[25. 16.  9.  4.  1.]
 [ 0.  1.  4.  9. 16.]]
```
does it? If not your cupy install is broken and you should fix that before running the test suite of this software

**Comment by jinxsfe** [comment]
![image](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/121477741/80cd044c-4888-4679-9973-127459199e03)
I run the code as you provided, it print it  but I stilll failed

**Comment by sroet** [comment]
Which version of the code are you running? Our current test suite should be 20 tests (as in your previous error), and not 18 as show in the screenshot above

**Comment by jinxsfe** [comment]
I chnage angle diff to 8 instead of  0, and result show belo, does that ok now 
![image](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/121477741/58ecb960-f591-45af-88f1-b3f6bf10ef36)

**Comment by sroet** [comment]
I am still confused about the `Ran 18 tests`, which should be `Ran 20 tests` on the current version of the code. 

Also, that test checks that the results don't change when splitting the volume, which it really shouldn't. So, you altering the test doesn't actually solve the issue our code seems to be having on your machine

**Comment by jinxsfe** [comment]
first I install conda activate pytom_tm, after active environment , I install cupy via " conda install -c conda-forge cupy", I guess why Ran20 become R18, "Which version of the code are you running" what's mean for that ? you mean cupy version?

**Comment by sroet** [comment]
> "Which version of the code are you running" what's mean for that ? you mean cupy version?

No, I mean the version of the template matching code. Please run `git pull` from inside the code directory to update to the latest version since you did `git clone`

> Do you mind help me with ZOOM? we can set a meeting if you are avaliable, my email is [rjincheng840@gmail.com](mailto:rjincheng840@gmail.com)

I won't have time for the rest of my workday. Which timezone are you in and what are your available hours/days?

**Comment by jinxsfe** [comment]
" Which timezone are you in and what are your available hours/days?",  my time zoon is NewYork time, now is 1:38 PM, and I am available all times except the afternoon from 3:00~7:00 on Tuesday and Thursday

**Comment by jinxsfe** [comment]
![image](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/121477741/e0686b0e-57e1-4c28-a4e0-74ec0eb3197a)

**Comment by jinxsfe** [comment]
![image](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/121477741/625b7b57-d766-4365-b2db-467a34a635e1)
at now is Ran20, but still failed,

**Comment by sroet** [comment]
Sorry, my update instructions were incomplete, please also rerun the `python -m pip install '.[plotting]'` install instructions (from the main git directory). Let me know if that does not solve the issues. 

> my time zoon is NewYork time, now is 1:38 PM, and I am available all times except the afternoon from 3:00~7:00 on Tuesday and Thursday

If the above instructions do not solve the issue then I will have some time to have a zoom meeting at 11 AM - 12 PM your time zone (17-18 my local time) today (Jan 30th 2024)

**Comment by sroet** [comment]
> If the above instructions do not solve the issue then I will have some time to have a zoom meeting at 11 AM - 12 PM your time zone (17-18 my local time (GMT+1) ) today (Jan 30th 2024)

@jinxsfe I just send you an email with an invite for a teams meeting in about 45 min :)

**Comment by jinxsfe** [comment]
Hi, sorry, I just finished my work, do you have free time on Jan 31? you can send me teams meeting for js22bp@fsu.edu, and previous emails. appreciate

**Comment by jinxsfe** [comment]
@sroet

**Comment by sroet** [comment]
> Hi, sorry, I just finished my work, do you have free time on Jan 31?

I will give you a call on teams (on the above .edu address) at 11 AM in your time zone (17 my local time (GMT+1) ) today (Jan 31th 2024) I will move the rest of the planning to the teams conversation with the .edu address , and post anything relevant to the codebase into this issue.

> @sroet 

I don't appreciate you @ me in this issue (I keep track of it during my work hours) and especially not at 4:33 AM in my timezone

**Comment by McHaillet** [comment]
@sroet, can we close this issue?

**Comment by sroet** [comment]
Most of the stuff has been resolved, so closing for now
