### ISSUE TITLE
angular sampling options

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#92]
It would be good if there were some more options for choosing angular increments in searches. Especially for exhaustive searches: the most exhaustive is 3. degrees, while the second most exhaustive is 7. degrees. Here it would be important if users have availability for a 5. degrees increment searches.

Ideally they could be generated on the fly, but a smaller solution could already be to just include an added 5 degrees increment search.

**Comment by sroet** [comment]
During an offline discussion, we will be matching RELION and probably use [HEALPix](https://healpix.sourceforge.io/) for this. [The conda-forge feedstock](https://github.com/conda-forge/healpix-feedstock) seems currently active as well

**Comment by sroet** [comment]
After an offline meeting and testing some angle approximations we settled for the "square root of the average area of the pixels" as a good approximation for the angle difference between points:
```python
import healpix as hp
import numpy as np
def angle_to_nside(angle):
    #approx_angle = (4*np.pi/npix)**0.5 * 180/np.pi
    npix = 4*np.pi / (angle / 180 * np.pi)**2 
    while hp.nside2npix(i) < npix:
        i += 1
    return i

```
The investigation `.ipynb` is attached in [test_healpix.zip](https://github.com/SBC-Utrecht/pytom-match-pick/files/14979728/test_healpix.zip) as well

**Comment by sroet** [comment]
> The investigation .ipynb is attached in [test_healpix.zip](https://github.com/SBC-Utrecht/pytom-match-pick/files/14979728/test_healpix.zip) as well (we did notice some instability with the great circle distance computation so take the numbers with a grain of salt)

This ipynb did not account for the conversion needed between `lon lat` and `theta phi`. A new investigation `.ipynb` is attached again [new_test_healpix.zip](https://github.com/SBC-Utrecht/pytom-match-pick/files/15129500/test_healpix.zip)
It shows that the "square root of the average area" is a good approximation of the median angle (even getting better for smaller median angles),
