### ISSUE TITLE
template matching might fail silently when unavailable gpu's are specified

### ISSUE THREAD

**Issue by sroet** [SBC-Utrecht/pytom-match-pick#99]
As title, and I am getting some reports that it might actually fail silently if users try to run the commands with `-g 0 1 2 3`

**Comment by McHaillet** [comment]
Oh that is not good. I can easily update the tutorial to use a single GPU, but this should not be failing silently.

**Comment by McHaillet** [comment]
add the issue for tutorial to a list of some update, see issue #102.
Will change the title here to tutorial failing silently
